---
- name: Ensure fly is installed
  shell: "which fly"
  register: result
  ignore_errors: true

- fail:
    msg: "Fly cli is not found! You need to install it first."
  when: result.rc != 0

- name: Login Concourse
  shell: fly login -t {{ CONCOURSE.TARGET }} -c {{ CONCOURSE.URL }}  -u {{ CONCOURSE.USERNAME }} -p {{ CONCOURSE.PASSWORD }}

- name: Transfer Concourse scripts
  copy:
    src: "./files/create_concourse.sh"
    dest: "/home/guyzsarun/ansible/"
    mode: "0777"

- name: Transfer Concourse Pipeline
  copy:
    src: "./files/pipeline.yaml"
    dest: "/home/guyzsarun/ansible/"
    mode: "0777"

- name: Transfer Github username file
  copy:
    src: "./files/github_username.txt"
    dest: "/home/guyzsarun/ansible/"
    mode: "0777"

- name: Execute the script
  command: chdir=/home/guyzsarun/ansible  ./create_concourse.sh github_username.txt {{ DOCKER.USERNAME }} {{ DOCKER.PASSWORD }} {{ K8S.URL }} {{ K8S.CA }} {{ K8S.TOKEN }} {{ CONCOURSE.TARGET }}
